### ISSUE TITLE
Make a Logo for this Project

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#101]
only requirements are should be minimal and should represent this project theme ('box shadows')

**Comment by ridbay** [comment]
Hi, I can handle this.
Should I go ahead?

**Comment by nakulrathore** [comment]
yes @ridbay, go ahead. , if you are working this actively, should i assign this to you?

**Comment by nakulrathore** [comment]
and i'm stealing "We're all born naked, the rest is CSS and Javascript." if you don't mind :laughing:

**Comment by nakulrathore** [comment]
@ridbay, are you still working on this, please let me know, if true, ill assign this to you.

**Comment by ridbay** [comment]
> and i'm stealing "We're all born naked, the rest is CSS and Javascript." if you don't mind 😆

Go ahead 😆😆😆

**Comment by ridbay** [comment]
> @ridbay, are you still working on this, please let me know, if true, ill assign this to you.

Yes, please

**Comment by nakulrathore** [comment]
@ridbay , please update the progress on this issue.

**Comment by jkvyff** [comment]
Heya, If you just want I made a quick Logo using border styles. Easily editable as I made it in `html/css`
<img width="206" alt="Screen Shot 2019-10-24 at 11 02 31 PM" src="https://user-images.githubusercontent.com/8835646/67546942-78a1ec00-f6b2-11e9-827a-023c1b4f48ac.png">

**Comment by jkvyff** [comment]
@nakulrathore, I tried incorporating your feedback and commented on the original pull request, let me know what you think, and if that is the best place to comment or continue on the issue page.
