### ISSUE TITLE
add colors to background color buttons

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#12]
add colors to background change buttons, so user can easily switch to desired bg without going through all the BGs,
see bg colors here : src/background.js

**Comment by Spotts9** [comment]
I'd like to work on this one

**Comment by nakulrathore** [comment]
Hi @Spotts9 , @angelFQC already requested a merge for this , you can work on it more if you want to 
like remove unnecessary backgrounds , add your own styling for buttons etc.
