### ISSUE TITLE
Fix blur on hover

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#137]
in between the hover start and end state, the box and text blurrs
possible solutions :
-make the transition fast  
-remove the transition
-fix burr via css or js hack

**Comment by chadramsey** [comment]
I can take a look at this.

**Comment by nakulrathore** [comment]
@chadramsey sure.

**Comment by nsinghal12** [comment]
Working on it now.

**Comment by nakulrathore** [comment]
@nsinghal12 , this issue is still open, you can make a PR if you find any solution.

**Comment by deniskond** [comment]
Added a PR with my solution for this: https://github.com/nakulrathore/Box-Shadows/pull/144
