### ISSUE TITLE
Add color picker for background color.

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#14]
add color picker (any type) with background changer buttons, letting user choose any color for bg

**Comment by poojakp94** [comment]
@nakulrathore I would like to work on this.

**Comment by aldrenalangcao** [comment]
Would want to work on this too.

**Comment by nakulrathore** [comment]
@aldrenalangcao , requested changes for this on your commit ,
this issue is still "up for grabs"
