### ISSUE TITLE
Improve SEO 

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#19]
Commit whatever you think is best for SEO

**Comment by Thuvan96** [comment]
Can i work on this ??

**Comment by nakulrathore** [comment]
@Thuvan96 , sure :100:

**Comment by Lawrence4code** [comment]
I can contribute to this, is this still open?

**Comment by nakulrathore** [comment]
@Thuvan96, are you still working on this?
if not please let us know.

**Comment by Thuvan96** [comment]
On Wed, Oct 9, 2019 at 1:19 PM, Narendra Singh <notifications@github.com>
wrote:

> @Thuvan96 <https://github.com/Thuvan96>, are you still working on this?
> if not please let us know.
>
> —  Hey
>
   I am finished working on this

**Comment by LuisPinedaJR** [comment]
Is this still open, I'd like to contribute some SEO :)

**Comment by nakulrathore** [comment]
@LuisPinedaJR , ye this issue is "always open"
@Thuvan96 please make a pr of your work

**Comment by Lawrence4code** [comment]
![Screen Shot 2019-10-11 at 10 57 06 PM](https://user-images.githubusercontent.com/23227030/66671846-90bd4880-ec7a-11e9-8a86-2676d646241a.png)

Hey as per image the website scores 100% on SEO, also no recommendation in https://gtmetrix.com for any SEO improvement. As you can see in the image there's scope for improvement in "Accessibility".
I'd like to work on it if that's okay with you and if it makes sense. Do let me know, thanks.

If you are looking for any specific in SEO, pls do advise.

**Comment by nakulrathore** [comment]
@Lawrence4code, thanx for the analysis, and yes you can pull for accessibility. 

Thanx again.
