### ISSUE TITLE
Great work! 

### ISSUE THREAD

**Issue by ashokdey** [nakulrathore/Box-Shadows#44]
Hello @nakulrathore, great to see your work. However, it would be really nice if you can directly add the link to GitHub repo in the hosted webpage. 

Also, let me know if you are looking out for collaborators, I can share about this in my group @knaxus

Thanks

**Comment by nakulrathore** [comment]
Hi @ashokdey,
There is a buttom on the webpage, below title, but its small one, ill make an issue about this so hacktober people can work on this.


Also yes, im looking for collaborators, and if you have any idea or project you are working on, i would love to collaborate with you.

**Comment by ashokdey** [comment]
> Hi @ashokdey,
> There is a buttom on the webpage, below title, but its small one, ill make an issue about this so hacktober people can work on this.
> 
> Also yes, im looking for collaborators, and if you have any idea or project you are working on, i would love to collaborate with you.

Cool. Do share your contact details.

**Comment by nakulrathore** [comment]
hi @ashokdey ,
nakulrathore@outlook.com
+918890650788

le me know when you get this , ill delete this msg.
