### ISSUE TITLE
Review Background colors to show box-shadows more nicely and clearly

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#5]
edit `src/background.js`
make change with required colors

**Comment by 6lack6ix** [comment]
I want to work on it

**Comment by vxdiazdel** [comment]
I'd like to work on this. Can you tell me exactly what you're looking for here?

**Comment by nakulrathore** [comment]
yes @vxdiazdel , see there are some dark background colors, when we switch to them, we cant see almost any of the shadow, so we don't need those dark bg colors

-also, we want some of the practical background colors, like LinkedIn uses "#f5f5f5" for their bg.
