### ISSUE TITLE
Remove shadows with more then 1px borders

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#52]

**Comment by da201501181** [comment]
@nakulrathore Didn't get it, can you please elaborate?

**Comment by nakulrathore** [comment]
@da201501181, some boxes have borders more then 1pixels and should be removed because this project focuses more on shadows then borders.

checkout box named "solid new"

**Comment by da201501181** [comment]
@nakulrathore Can I take this up?

**Comment by nakulrathore** [comment]
@da201501181 , yes

**Comment by da201501181** [comment]
#55
