### ISSUE TITLE
Add github ribbon

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#62]
add github ribbon on webpage, it should be minimal and should match style of project.
ribbon can be placed anywhere, should not block any content and be mobile friendly.

**Comment by Sabihashaik** [comment]
Hi!
I'd like to work on this issue  😄

**Comment by nakulrathore** [comment]
@Sabihashaik , yes sure.

**Comment by Sabihashaik** [comment]
@nakulrathore Should I add the relevant CSS to index.css or App.css?

**Comment by nakulrathore** [comment]
ribbon should be in react files not in index.html file,
css will go to App.css

**Comment by Sabihashaik** [comment]
Ok, just to be clear, I'll have to create a react component for the Github ribbon in /src/components and add a class to render the component in App.js & its place its css in App.css?

A bit new to react so asking questions to understand the project structure better.

**Comment by nakulrathore** [comment]
yes that's the correct approach,
also if you get stuck anywhere just let me know, ill help you out.

we all were beginners when we started :)

**Comment by nakulrathore** [comment]
@all-contributors please add @Sabihashaik  for code

**Comment by Sabihashaik** [comment]
@nakulrathore Pl. let me know if there are any issues or changes to be made 😄

**Comment by nakulrathore** [comment]
We are no longer going with ribbon, it will be minimal github icon near title, we are working on designe, thank you for your contribution. We appreciate it.

**Comment by Sabihashaik** [comment]
@nakulrathore I see, thank you for letting me know.
