### ISSUE TITLE
Background color switcher blocking last box on mobile view

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#64]

**Comment by rohitgeddam** [comment]
I want to work on this.

**Comment by rohitgeddam** [comment]
i see that the color switcher is blocking boxes in mobile view.
Any suggestions on how to improve upon this.

**Comment by nakulrathore** [comment]
@rohitgeddam , just add space at the bottom of body, in this case maybe its padding bottom

**Comment by rohitgeddam** [comment]
DONE!! added padding-bottom and some margin to left and right as the google search bar was right up against the screen in mobile view

**Comment by rohitgeddam** [comment]
One more thing!
Shall i shift the content of Change Background bar to center, It would look nicer in my opinion.

**Comment by rohitgeddam** [comment]
removing margin from body and adding padding-bottom:120px does the trick

**Comment by nakulrathore** [comment]
Its been fixed
