### ISSUE TITLE
Add color picker for background color.

### ISSUE THREAD

**Issue by nakulrathore** [nakulrathore/Box-Shadows#65]
user should be able to add/type hex color for background.
or use the color picker to pick background color.

picker should be minimal with hex input box.

**Comment by kylewetton** [comment]
Hey man, I could help with this. Whereabouts do you want a hex colour picker?

**Comment by kylewetton** [comment]
Here's a pen I did that uses 3 of them

https://codepen.io/kylewetton/pen/OJLmJoV

**Comment by nakulrathore** [comment]
@kylewetton, that pen example is great, we want something like this with one input and a color picker

**Comment by kylewetton** [comment]
All good to place it inside the color tray in attached to the bottom of the viewport?

**Comment by kylewetton** [comment]
More specifically would you like to keep the preset colours or remove those and opt in just for a hex picker?

**Comment by nakulrathore** [comment]
@kylewetton yes, please attatch it to the bottom tray and keep the available bg colors
